name: Docker Build Test

on: push

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t spoofpy .

    - name: Test Docker Image
      run: |
        docker run spoofpy --version