version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    network_mode: "host"
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bluecat8182@outlook.com"
      PGADMIN_DEFAULT_PASSWORD: "P@ssw0rd"
    ports:
      - "80:80"
volumes:
  db-data: