version: '3'
services:
  db:
    container_name: db
    hostname: db
    networks:
      - spoofpy-net
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - spoofpy-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"
volumes:
  spoofpy-db-data:

networks:
  spoofpy-net:
    name: spoofpy-net
    driver: host
    driver_opts:
      parent: wifi0
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          ip_range: ${NETWORK_IP_RANGE}
          gateway: ${NETWORK_GATEWAY}
  spoofpy-internal-net:
    name: spoofpy-internal-net
    driver: bridge
