version: '3'
services:
  app:
    container_name: spoofpy-app
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - db
    networks:
      - spoofpy-net
    links:
      - db:db
    volumes:
      - .:/app
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
  db:
    container_name: db
    hostname: db
    networks:
      - spoofpy-net
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - spoofpy-db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"
volumes:
  spoofpy-db-data:

networks:
  spoofpy-net:
    name: spoofpy-net
    driver: macvlan
    driver_opts:
      parent: wifi0
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          ip_range: ${NETWORK_IP_RANGE}
          gateway: ${NETWORK_GATEWAY}
  spoofpy-internal-net:
    name: spoofpy-internal-net
    driver: bridge
